-- v7.2 "User-level moderation": progressive account enforcement
-- (restrict/temporarily suspend/permanently ban), private bank-addition
-- attribution, and an admin-initiated account-deletion workflow — see
-- the v7.2 plan for the full design/review history behind every choice
-- below. Bundles a new feature's table+function+trigger-extension changes
-- into one migration, same precedent as 20260713060000_add_admin_moderation.sql.

-- ============================================================
-- Schema
-- ============================================================

-- Row persists permanently once a user is ever acted on (including
-- through reactivation to 'active') — this is what gives the Auth-sync
-- state and transition_id somewhere to live across a reactivation, and
-- gives the profile page real status history. No row = never moderated =
-- active (see getUserModerationStatus/the enforcement triggers below).
create table user_moderation_status (
  user_id uuid primary key references auth.users(id) on delete cascade,
  status text not null check (status in ('active', 'restricted', 'temporarily_banned', 'permanently_banned')),
  reason_category text not null check (reason_category in ('spam', 'fabricated', 'duplicate', 'privacy', 'abuse', 'harassment', 'other')),
  note text not null check (length(note) between 1 and 500),
  ban_expires_at timestamptz,
  moderator_user_id uuid references auth.users(id) on delete set null,
  -- Regenerated by moderate_set_user_status on every transition. An
  -- Auth-sync attempt only ever writes its result if this still matches
  -- what it started with — see lib/authSync.ts's reconcileAuthSync.
  transition_id uuid not null default gen_random_uuid(),
  auth_sync_status text not null default 'pending' check (auth_sync_status in ('synced', 'pending')),
  auth_sync_error text check (auth_sync_error is null or length(auth_sync_error) <= 300),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint user_moderation_status_temp_ban_has_expiry check (status <> 'temporarily_banned' or ban_expires_at is not null),
  constraint user_moderation_status_non_temp_no_expiry check (status = 'temporarily_banned' or ban_expires_at is null)
);
alter table user_moderation_status enable row level security;
-- Zero policies — service-role only, same as moderation_actions/route_requests.

-- Private bank-addition attribution. banks.* is publicly SELECT-able (see
-- rlsManifest.mjs), so attribution can never live as a column on banks
-- itself without leaking it — RLS is row-level, not column-level.
create table bank_attributions (
  bank_id uuid primary key references banks(id) on delete cascade,
  added_by_user_id uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now()
);
alter table bank_attributions enable row level security;
-- Zero policies — service-role only.

-- target_id becomes nullable: content-deletion actions keep it (the
-- removed row's own id, which isn't a personal identifier and has no
-- erasure obligation); user-level actions (status changes, account
-- deletion, email reveal) carry ONLY subject_user_id, which is what
-- actually gets erased via ON DELETE SET NULL when the account is
-- deleted. Populating target_id with a user's UUID for these actions
-- would permanently retain it (target_id has no FK/erasure behavior),
-- defeating the erasure subject_user_id is meant to guarantee.
alter table moderation_actions alter column target_id drop not null;
alter table moderation_actions add column subject_user_id uuid references auth.users(id) on delete set null;

-- Dynamically discover and drop each existing single-column CHECK
-- constraint by its actual name rather than assuming Postgres's default
-- <table>_<column>_check naming — same "don't hardcode what pg_catalog
-- can tell you" precedent as the policy-drop loop in
-- 20260710233000_lock_down_report_table_reads.sql.
do $$
declare
  v_conname text;
begin
  select con.conname into v_conname
  from pg_constraint con
  join pg_attribute att on att.attnum = con.conkey[1] and att.attrelid = con.conrelid
  where con.conrelid = 'public.moderation_actions'::regclass
    and con.contype = 'c'
    and array_length(con.conkey, 1) = 1
    and att.attname = 'action_type';
  if v_conname is not null then
    execute format('alter table moderation_actions drop constraint %I', v_conname);
  end if;
end $$;
alter table moderation_actions add constraint moderation_actions_action_type_check
  check (action_type in ('delete', 'restrict', 'suspend', 'ban', 'reactivate', 'delete_account', 'reveal_email'));

do $$
declare
  v_conname text;
begin
  select con.conname into v_conname
  from pg_constraint con
  join pg_attribute att on att.attnum = con.conkey[1] and att.attrelid = con.conrelid
  where con.conrelid = 'public.moderation_actions'::regclass
    and con.contype = 'c'
    and array_length(con.conkey, 1) = 1
    and att.attname = 'target_table';
  if v_conname is not null then
    execute format('alter table moderation_actions drop constraint %I', v_conname);
  end if;
end $$;
alter table moderation_actions add constraint moderation_actions_target_table_check
  check (target_table in ('route_reports', 'edd_reports', 'route_requests', 'user_moderation_status', 'auth_users'));

do $$
declare
  v_conname text;
begin
  select con.conname into v_conname
  from pg_constraint con
  join pg_attribute att on att.attnum = con.conkey[1] and att.attrelid = con.conrelid
  where con.conrelid = 'public.moderation_actions'::regclass
    and con.contype = 'c'
    and array_length(con.conkey, 1) = 1
    and att.attname = 'reason_category';
  if v_conname is not null then
    execute format('alter table moderation_actions drop constraint %I', v_conname);
  end if;
end $$;
alter table moderation_actions add constraint moderation_actions_reason_category_check
  check (reason_category in ('spam', 'fabricated', 'duplicate', 'privacy', 'abuse', 'harassment', 'other'));

-- Content-deletion actions must carry target_id (the removed row's own
-- id); user-level actions must not (their only identifier is
-- subject_user_id, which is erasable). Prevents a future insert from
-- accidentally putting a user's UUID somewhere erasure can't reach.
alter table moderation_actions add constraint moderation_actions_target_shape_check check (
  (target_table in ('route_reports', 'edd_reports', 'route_requests') and target_id is not null)
  or
  (target_table in ('user_moderation_status', 'auth_users') and target_id is null)
);

-- ============================================================
-- Atomic bank creation + attribution
-- ============================================================

-- addBank.ts previously did two separate calls (insert banks, then insert
-- attribution) — a failure on the second call after a successful first
-- would silently recreate the exact "unattributed submission" problem
-- this feature exists to close. One transaction closes that gap.
create or replace function add_bank_with_attribution(p_name text, p_slug text, p_user_id uuid)
returns table(id uuid, slug text, name text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_bank_id uuid;
begin
  insert into banks (name, slug) values (p_name, p_slug) returning banks.id into v_bank_id;
  insert into bank_attributions (bank_id, added_by_user_id) values (v_bank_id, p_user_id);
  return query select v_bank_id, p_slug, p_name;
end;
$$;

revoke all on function public.add_bank_with_attribution(text, text, uuid) from public;
revoke all on function public.add_bank_with_attribution(text, text, uuid) from anon;
revoke all on function public.add_bank_with_attribution(text, text, uuid) from authenticated;

-- ============================================================
-- User status changes
-- ============================================================

create or replace function moderate_set_user_status(
  p_user_id uuid,
  p_moderator_id uuid,
  p_status text,
  p_reason text,
  p_reason_category text,
  p_ban_hours integer default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_previous_status text;
  v_action_type text;
  v_transition_id uuid;
begin
  if p_user_id = p_moderator_id then
    raise exception 'cannot moderate your own account' using errcode = 'P0003';
  end if;

  if p_status not in ('active', 'restricted', 'temporarily_banned', 'permanently_banned') then
    raise exception 'invalid status: %', p_status using errcode = 'P0001';
  end if;

  if p_status = 'temporarily_banned' and (p_ban_hours is null or p_ban_hours < 1 or p_ban_hours > 8760) then
    raise exception 'temporarily_banned requires p_ban_hours between 1 and 8760' using errcode = 'P0001';
  end if;

  -- Serializes concurrent status changes for this exact user so a second
  -- call's "previous status" always reflects the first call's committed
  -- result, not a stale pre-first-call read — same technique as
  -- moderate_delete_submission's pair-level lock
  -- (20260714010000_fix_moderate_delete_submission_reopen_scope.sql).
  -- This protects the write below; it does NOT extend to the external
  -- Supabase Auth call the caller makes afterward — see
  -- lib/authSync.ts's reconcileAuthSync for how that race is handled.
  perform pg_advisory_xact_lock(hashtext('user_moderation_status'), hashtext(p_user_id::text));

  select status into v_previous_status from user_moderation_status where user_id = p_user_id;
  v_previous_status := coalesce(v_previous_status, 'active');

  v_transition_id := gen_random_uuid();

  insert into user_moderation_status (
    user_id, status, reason_category, note, ban_expires_at, moderator_user_id,
    transition_id, auth_sync_status, auth_sync_error, updated_at
  )
  values (
    p_user_id, p_status, p_reason_category, p_reason,
    case when p_status = 'temporarily_banned' then now() + make_interval(hours => p_ban_hours) else null end,
    p_moderator_id, v_transition_id, 'pending', null, now()
  )
  on conflict (user_id) do update set
    status = excluded.status,
    reason_category = excluded.reason_category,
    note = excluded.note,
    ban_expires_at = excluded.ban_expires_at,
    moderator_user_id = excluded.moderator_user_id,
    transition_id = excluded.transition_id,
    auth_sync_status = excluded.auth_sync_status,
    auth_sync_error = excluded.auth_sync_error,
    updated_at = now();

  v_action_type := case p_status
    when 'active' then 'reactivate'
    when 'restricted' then 'restrict'
    when 'temporarily_banned' then 'suspend'
    else 'ban'
  end;

  insert into moderation_actions
    (moderator_user_id, action_type, target_table, target_id, subject_user_id, reason, reason_category, snapshot)
  values (
    p_moderator_id, v_action_type, 'user_moderation_status', null, p_user_id, p_reason, p_reason_category,
    jsonb_build_object('previous_status', v_previous_status, 'resulting_status', p_status)
  );

  return v_transition_id;
end;
$$;

revoke all on function public.moderate_set_user_status(uuid, uuid, text, text, text, integer) from public;
revoke all on function public.moderate_set_user_status(uuid, uuid, text, text, text, integer) from anon;
revoke all on function public.moderate_set_user_status(uuid, uuid, text, text, text, integer) from authenticated;

-- ============================================================
-- moderate_delete_submission: third revision — capture subject_user_id
-- ============================================================

-- Copies forward the full body from
-- 20260714010000_fix_moderate_delete_submission_reopen_scope.sql
-- unchanged (including the pair-level advisory lock and reopen-scope
-- fix), adding only: capture the target row's user_id into
-- v_subject_user_id and pass it through to the audit insert. The JSON
-- snapshot stays exactly as it is today (identity-free) — this is a
-- separate, dedicated, FK-backed column, not a change to that
-- convention. target_id/target_table are unaffected (content-deletion
-- actions, first branch of moderation_actions_target_shape_check above).
create or replace function moderate_delete_submission(
  p_target_table text,
  p_target_id uuid,
  p_moderator_id uuid,
  p_reason text,
  p_reason_category text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_snapshot jsonb;
  v_pair_from uuid;
  v_pair_to uuid;
  v_remaining_reports int;
  v_deleted_count int;
  v_subject_user_id uuid;
begin
  if p_target_table not in ('route_reports', 'edd_reports', 'route_requests') then
    raise exception 'invalid target_table: %', p_target_table using errcode = 'P0001';
  end if;

  if p_target_table = 'route_reports' then
    select jsonb_build_object(
      'from_bank_id', from_bank_id, 'from_bank_name', from_bank_name,
      'to_bank_id', to_bank_id, 'to_bank_name', to_bank_name,
      'rail_used', rail_used, 'direction', direction, 'status', status,
      'tested_at', tested_at, 'settlement_time_minutes', settlement_time_minutes,
      'same_day', same_day, 'notes', notes, 'created_at', created_at
    ), from_bank_id, to_bank_id, user_id
    into v_snapshot, v_pair_from, v_pair_to, v_subject_user_id
    from route_reports where id = p_target_id;
  elsif p_target_table = 'edd_reports' then
    select jsonb_build_object(
      'bank_id', bank_id, 'days_early', days_early,
      'deposit_type', deposit_type, 'payroll_provider', payroll_provider,
      'created_at', created_at
    ), user_id
    into v_snapshot, v_subject_user_id from edd_reports where id = p_target_id;
  else
    select jsonb_build_object('from_bank_id', from_bank_id, 'to_bank_id', to_bank_id, 'created_at', created_at), user_id
    into v_snapshot, v_subject_user_id from route_requests where id = p_target_id;
  end if;

  if v_snapshot is null then
    raise exception 'not_found' using errcode = 'P0002';
  end if;

  if p_target_table = 'route_reports' and p_reason_category in ('spam', 'fabricated') then
    perform pg_advisory_xact_lock(hashtext(v_pair_from::text), hashtext(v_pair_to::text));

    select count(*) into v_remaining_reports
    from route_reports
    where from_bank_id = v_pair_from and to_bank_id = v_pair_to
      and user_id is not null and id <> p_target_id;

    if v_remaining_reports = 0 then
      with candidates as (
        select distinct on (user_id) id, user_id
        from route_requests
        where from_bank_id = v_pair_from and to_bank_id = v_pair_to
          and fulfilled_at is not null
        order by user_id, created_at desc, id desc
      ),
      eligible as (
        select c.id
        from candidates c
        where not exists (
          select 1 from route_requests active
          where active.from_bank_id = v_pair_from and active.to_bank_id = v_pair_to
            and active.user_id is not distinct from c.user_id
            and active.fulfilled_at is null
        )
      )
      update route_requests
      set fulfilled_at = null, fulfilled_by_report_id = null
      where id in (select id from eligible);
    end if;
  end if;

  execute format('delete from %I where id = $1', p_target_table) using p_target_id;
  get diagnostics v_deleted_count = row_count;

  if v_deleted_count = 0 then
    raise exception 'not_found' using errcode = 'P0002';
  end if;

  insert into moderation_actions
    (moderator_user_id, action_type, target_table, target_id, subject_user_id, reason, reason_category, snapshot)
  values (p_moderator_id, 'delete', p_target_table, p_target_id, v_subject_user_id, p_reason, p_reason_category, v_snapshot);
end;
$$;
-- CREATE OR REPLACE preserves the function's OID/ACL — the
-- public/anon/authenticated revokes from 20260713060000 still hold.

-- ============================================================
-- Ban/restriction enforcement in the existing quota triggers
-- ============================================================

create or replace function check_route_report_quota()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_count integer;
begin
  if new.user_id is null then
    return new;
  end if;

  if exists (
    select 1 from user_moderation_status
    where user_id = new.user_id
      and (status in ('restricted', 'permanently_banned')
           or (status = 'temporarily_banned' and ban_expires_at > now()))
  ) then
    raise exception 'Your account is currently restricted from submitting route reports.'
      using errcode = 'P0001';
  end if;

  new.created_at := now();

  perform pg_advisory_xact_lock(hashtext('route_reports_quota'), hashtext(new.user_id::text));

  select count(*) into recent_count
  from route_reports
  where user_id = new.user_id
    and created_at > now() - interval '10 minutes';

  if recent_count >= 20 then
    raise exception 'Too many route reports submitted recently. Please wait a few minutes and try again.'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

create or replace function check_edd_report_quota()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  recent_count integer;
begin
  if new.user_id is null then
    return new;
  end if;

  if exists (
    select 1 from user_moderation_status
    where user_id = new.user_id
      and (status in ('restricted', 'permanently_banned')
           or (status = 'temporarily_banned' and ban_expires_at > now()))
  ) then
    raise exception 'Your account is currently restricted from submitting EDD reports.'
      using errcode = 'P0001';
  end if;

  new.created_at := now();

  perform pg_advisory_xact_lock(hashtext('edd_reports_quota'), hashtext(new.user_id::text));

  select count(*) into recent_count
  from edd_reports
  where user_id = new.user_id
    and created_at > now() - interval '10 minutes';

  if recent_count >= 10 then
    raise exception 'Too many EDD reports submitted recently. Please wait a few minutes and try again.'
      using errcode = 'P0001';
  end if;

  return new;
end;
$$;

notify pgrst, 'reload schema';
